# Generated by Django 4.2.1 on 2024-12-17 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0002_commentedmixin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('commentedmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comments.commentedmixin')),
                ('title', models.CharField(max_length=100)),
                ('title_img', models.ImageField(upload_to='threads/images/')),
                ('data', models.TextField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('comments.commentedmixin',),
        ),
    ]
