# Generated by Django 4.2.1 on 2024-12-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title_img',
            field=models.ImageField(blank=True, null=True, upload_to='threads/images/'),
        ),
    ]
