# Generated by Django 4.2.1 on 2024-12-24 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        ('threads', '0002_alter_thread_data_alter_thread_title_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='treads', to='boards.board'),
            preserve_default=False,
        ),
    ]
