# Generated by Django 4.2.1 on 2024-12-14 17:41

from django.db import migrations


def fill_fk(apps, schema_editor):
    Message = apps.get_model('threads', 'Message')
    ThreadModel = apps.get_model('boards', 'ThreadModel')
    thread = ThreadModel.objects.get(pk=1)
    for msg in Message.objects.all():
        msg.thread = thread
        msg.save()


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_message_thread'),
    ]

    operations = [
        migrations.RunPython(fill_fk),
    ]
