# Generated by Django 4.2.1 on 2024-12-23 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commentedmixin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachedimage',
            old_name='message',
            new_name='comment',
        ),
    ]
