# Generated by Django 4.2.1 on 2024-12-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_img', models.ImageField(upload_to='threads/images/')),
                ('data', models.TextField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
